#include "filesystem.h"

#include "root_directory.h" // This is a configuration file generated by CMake.

std::string const & FileSystem::getRoot()
  {
    static char const * envRoot = getenv("LOGL_ROOT_PATH");
    static char const * givenRoot = (envRoot != nullptr ? envRoot : logl_root);
    static std::string root = (givenRoot != nullptr ? givenRoot : "");
    return root;
  }